# Generated by Django 5.2.1 on 2025-05-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_options_alter_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='short_description',
            field=models.TextField(max_length=1000),
        ),
    ]
