# Generated by Django 5.2.1 on 2025-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_blog_body_alter_blogs_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
